import React, { useEffect, useRef, useState } from 'react';
import { AnalysisResult } from '../types';
import { 
  LightBulbIcon, 
  UserGroupIcon,
  ChatBubbleBottomCenterTextIcon,
  ListBulletIcon,
  DocumentTextIcon,
  PresentationChartLineIcon,
  BeakerIcon,
  ArrowsRightLeftIcon,
  CubeIcon
} from '@heroicons/react/24/outline';

declare global {
  interface Window {
    PptxGenJS: any;
    mermaid: any;
  }
}

interface ResultsDashboardProps {
  data: AnalysisResult;
}

// Isolated Mermaid Component to handle diagram rendering with better error handling
const MermaidChart: React.FC<{ chart: string }> = React.memo(({ chart }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const renderChart = async () => {
      if (window.mermaid && containerRef.current && chart) {
        try {
          setError(null);
          window.mermaid.initialize({ 
            startOnLoad: false, 
            theme: 'neutral', 
            securityLevel: 'loose',
            fontFamily: 'Inter, sans-serif'
          });
          
          containerRef.current.innerHTML = '';
          
          // Clean up chart string one last time before rendering
          let cleanChart = chart.replace(/```mermaid/g, '').replace(/```/g, '').trim();
          
          // Generate unique ID
          const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
          
          // Use mermaid.render API which is safer than running on element
          const { svg } = await window.mermaid.render(id, cleanChart);
          containerRef.current.innerHTML = svg;
          
        } catch (err: any) {
          console.error('Mermaid rendering error:', err);
          // Display a fallback message or specific error
          setError("逻辑图生成失败，可能是语法问题。");
          if (containerRef.current) {
             containerRef.current.innerHTML = `<div class="text-red-500 text-xs p-2 bg-red-50 rounded border border-red-100 font-mono overflow-auto">Error rendering diagram. Raw code:<br/>${chart}</div>`;
          }
        }
      }
    };

    renderChart();
  }, [chart]);

  return (
    <div className="w-full">
      <div ref={containerRef} className="w-full overflow-x-auto flex justify-center py-6 bg-white rounded-lg min-h-[100px]" />
      {error && <p className="text-center text-xs text-red-400 mt-2">{error}</p>}
    </div>
  );
});

const ResultsDashboard: React.FC<ResultsDashboardProps> = React.memo(({ data }) => {
  
  const handleExportPPT = () => {
    if (!window.PptxGenJS) {
      alert("PPT 生成库加载失败，请刷新页面重试。");
      return;
    }

    const pptx = new window.PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';
    pptx.title = '问卷分析报告';

    pptx.defineSlideMaster({
      title: "REPORT_MASTER",
      background: { color: "FFFFFF" },
      objects: [
        { rect: { x: 0, y: 5.35, w: "100%", h: 0.05, fill: { color: "E5E7EB" } } },
        { text: { text: "Generated by 问卷洞察 AI", x: 0.5, y: 5.45, w: 4, h: 0.3, fontSize: 9, color: "9CA3AF" } },
        { slideNumber: { x: 9.0, y: 5.45, fontSize: 9, color: "9CA3AF" } }
      ]
    });

    // Slide 1: Cover
    const slideCover = pptx.addSlide();
    slideCover.background = { color: "F3F4F6" };
    slideCover.addText("问卷洞察研究报告", { x: 0.5, y: '40%', w: '90%', fontSize: 44, bold: true, color: '1F2937', align: 'center' });
    slideCover.addText(`生成日期: ${new Date().toLocaleDateString()}`, { x: 0.5, y: '55%', w: '90%', fontSize: 18, color: '6B7280', align: 'center' });

    // Slide 2: Core Conclusions
    const slideConc = pptx.addSlide("REPORT_MASTER");
    slideConc.addText("研究核心结论", { x: 0.5, y: 0.4, w: '90%', fontSize: 24, bold: true, color: '4F46E5' });
    slideConc.addText(data.coreConclusions.overallConclusion, { x: 0.5, y: 1.0, w: '90%', h: 1.0, fontSize: 12, color: '374151' });
    
    // Modules
    data.coreConclusions.logicalModules.slice(0, 3).forEach((mod, i) => {
      const yPos = 2.2 + (i * 1.1);
      slideConc.addText(mod.title, { x: 0.5, y: yPos, fontSize: 14, bold: true, color: '1F2937' });
      slideConc.addText(mod.content, { x: 0.5, y: yPos + 0.3, w: '90%', fontSize: 11, color: '4B5563' });
    });

    // Slide 3: Actionable Insights
    const slideAction = pptx.addSlide("REPORT_MASTER");
    slideAction.addText("战略行动建议", { x: 0.5, y: 0.4, w: '90%', fontSize: 24, bold: true, color: '4F46E5' });
    data.coreConclusions.actionableInsights.forEach((insight, i) => {
      slideAction.addText(`${i + 1}. ${insight}`, { x: 0.5, y: 1.2 + (i * 0.6), w: '90%', fontSize: 14, color: '374151' });
    });

    // Slide 4: User Clusters
    const slideClusters = pptx.addSlide("REPORT_MASTER");
    slideClusters.addText("用户画像聚类", { x: 0.5, y: 0.4, w: '90%', fontSize: 24, bold: true, color: '4F46E5' });
    const colWidth = 3.0;
    data.userClusters.slice(0, 3).forEach((cluster, i) => {
      const xPos = 0.5 + (i * 3.1);
      slideClusters.addShape(pptx.ShapeType.rect, { x: xPos, y: 1.2, w: colWidth, h: 4.0, fill: { color: 'F9FAFB' }, line: { color: 'E5E7EB' } });
      slideClusters.addText(cluster.name, { x: xPos + 0.1, y: 1.4, w: colWidth - 0.2, fontSize: 16, bold: true, color: '1F2937' });
      slideClusters.addText(`占比: ~${cluster.percentage}%`, { x: xPos + 0.1, y: 1.8, fontSize: 11, color: '4F46E5' });
      slideClusters.addText(cluster.description, { x: xPos + 0.1, y: 2.1, w: colWidth - 0.2, fontSize: 10, color: '4B5563' });
    });

    // Slides for Questions
    data.questionInsights.forEach((qInsight, idx) => {
      const slideQ = pptx.addSlide("REPORT_MASTER");
      slideQ.addText(`Q${idx + 1}: ${qInsight.question}`, { x: 0.5, y: 0.4, w: '92%', h: 0.8, fontSize: 20, bold: true, color: '1F2937' });
      qInsight.corePoints.slice(0, 4).forEach((point, pIdx) => {
        const yBase = 1.4 + (pIdx * 1.0);
        slideQ.addText(`${point.label} (${point.percentage}%)`, { x: 0.6, y: yBase, fontSize: 14, bold: true, color: '374151' });
        slideQ.addText(point.description, { x: 0.6, y: yBase + 0.3, w: 8.8, fontSize: 11, color: '4B5563' });
        
        // Quotes with source
        if (point.quotes && point.quotes.length > 0) {
           point.quotes.slice(0, 2).forEach((q, qI) => {
             slideQ.addText(`${q.source}: "${q.text}"`, { 
                 x: 0.6, 
                 y: yBase + 0.8 + (qI * 0.18), 
                 w: 8.8, fontSize: 9, color: '6B7280', italic: true 
             });
           });
        }
      });
    });

    pptx.writeFile({ fileName: `Survey_Report.pptx` });
  };

  const handleExportWord = () => {
    const header = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><style>body { font-family: 'Microsoft YaHei'; }</style></head><body>`;
    const footer = "</body></html>";
    
    let content = `
      <h1>1. 研究核心结论</h1>
      <p><strong>1.1 综合发现</strong></p>
      <p>${data.coreConclusions.overallConclusion}</p>
      
      <h3>1.2 逻辑模块分析</h3>
      ${data.coreConclusions.logicalModules.map(m => `
        <div style="margin-bottom:15px; background:#f8fafc; padding:10px; border-radius:5px;">
          <strong>${m.title}</strong>
          <p>${m.content}</p>
        </div>
      `).join('')}

      <h3>1.3 战略行动建议</h3>
      <ol>
        ${data.coreConclusions.actionableInsights.map(i => `<li>${i}</li>`).join('')}
      </ol>

      <br style="page-break-before:always" />
      <h1>2. 用户画像聚类</h1>
      ${data.userClusters.map(c => `<p><strong>${c.name} (~${c.percentage}%)</strong>: ${c.description}</p>`).join('')}

      <br style="page-break-before:always" />
      <h1>3. 深度分题分析</h1>
      ${data.questionInsights.map(q => `
        <h3>${q.question}</h3>
        <ul>
          ${q.corePoints.map(p => `
            <li style="margin-bottom:10px;">
              <strong>${p.label}</strong> (${p.percentage}%): ${p.description}
              ${p.quotes.length > 0 ? `
                <br/>
                <span style="font-style:italic; color:#666; font-size:0.9em;">
                  ${p.quotes.map(qt => `[${qt.source}]: "${qt.text}"`).join('; ')}
                </span>
              ` : ''}
            </li>
          `).join('')}
        </ul>
      `).join('')}
    `;

    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(header + content + footer);
    const link = document.createElement("a");
    link.href = source;
    link.download = `Survey_Report.doc`;
    link.click();
  };

  return (
    <div className="space-y-10 animate-fade-in pb-12">
      
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <h2 className="text-2xl font-bold text-slate-900">分析报告仪表盘</h2>
        <div className="flex space-x-3">
          <button onClick={handleExportPPT} className="inline-flex items-center px-4 py-2 border border-slate-300 shadow-sm text-sm font-medium rounded-lg text-slate-700 bg-white hover:bg-slate-50">
            <PresentationChartLineIcon className="h-4 w-4 mr-2" /> PPT 报告
          </button>
          <button onClick={handleExportWord} className="inline-flex items-center px-4 py-2 border border-slate-300 shadow-sm text-sm font-medium rounded-lg text-slate-700 bg-white hover:bg-slate-50">
            <DocumentTextIcon className="h-4 w-4 mr-2" /> Word 报告
          </button>
        </div>
      </div>

      {/* Core Conclusions Section */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="p-8 border-b border-slate-100">
          <div className="flex items-center space-x-3 mb-6">
            <BeakerIcon className="h-7 w-7 text-indigo-600" />
            <h2 className="text-xl font-bold text-slate-900">研究核心结论</h2>
          </div>
          
          {/* Overall Conclusion */}
          <div className="mb-8 p-6 bg-indigo-50/30 rounded-xl border border-indigo-50">
            <h3 className="text-indigo-900 font-bold mb-2 text-lg">综合发现</h3>
            <p className="text-slate-700 leading-loose text-base">
              {data.coreConclusions.overallConclusion}
            </p>
          </div>

          {/* Logical Modules */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
            {data.coreConclusions.logicalModules.map((mod, idx) => (
              <div key={idx} className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow">
                <div className="flex items-center mb-3">
                  <CubeIcon className="h-5 w-5 text-indigo-500 mr-2" />
                  <h4 className="font-bold text-slate-800">{mod.title}</h4>
                </div>
                <p className="text-sm text-slate-600 leading-relaxed">{mod.content}</p>
              </div>
            ))}
          </div>

          {/* Actionable Insights (Integrated) */}
          <div className="mb-10 bg-amber-50/40 p-6 rounded-xl border border-amber-100">
            <div className="flex items-center text-slate-800 font-bold text-lg mb-4">
                <LightBulbIcon className="h-5 w-5 mr-2 text-amber-500" />
                战略行动建议
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {data.coreConclusions.actionableInsights.map((insight, idx) => (
                <div key={idx} className="flex items-start space-x-3 p-3 bg-white rounded-lg border border-amber-100 shadow-sm">
                  <span className="flex-shrink-0 mt-0.5 w-5 h-5 bg-amber-100 text-amber-600 rounded-full flex items-center justify-center text-xs font-bold">{idx + 1}</span>
                  <span className="text-slate-700 text-sm font-medium leading-relaxed">{insight}</span>
                </div>
              ))}
            </div>
          </div>

           {/* Logic Diagram */}
           <div>
             <div className="flex items-center text-slate-800 font-bold text-lg mb-4">
                <ArrowsRightLeftIcon className="h-5 w-5 mr-2 text-indigo-500" />
                逻辑影响路径图
             </div>
             <div className="bg-slate-50 border border-slate-200 rounded-xl p-2">
               <MermaidChart chart={data.coreConclusions.logicDiagramMermaid} />
             </div>
           </div>

        </div>
      </div>

      {/* User Clusters Section */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-8">
        <div className="flex items-center space-x-3 mb-8 border-b border-slate-100 pb-4">
          <UserGroupIcon className="h-7 w-7 text-indigo-600" />
          <h2 className="text-xl font-bold text-slate-900">用户画像聚类</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {data.userClusters.map((cluster, idx) => (
            <div key={idx} className="bg-slate-50 rounded-xl p-6 border border-slate-200">
              <div className="flex justify-between items-start mb-3">
                <h3 className="font-bold text-slate-900 text-lg">{cluster.name}</h3>
                <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-bold bg-indigo-100 text-indigo-800">~{cluster.percentage}%</span>
              </div>
              <p className="text-sm text-slate-600 mb-4 min-h-[3rem]">{cluster.description}</p>
              <div className="pt-4 border-t border-slate-200">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">包含用户</span>
                <div className="flex flex-wrap gap-2 max-h-24 overflow-y-auto custom-scrollbar">
                   {cluster.userIds.slice(0, 20).map((uid, i) => (
                     <span key={i} className="text-[10px] px-1.5 py-0.5 bg-white border rounded text-slate-500">{uid}</span>
                   ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Question Insights Section */}
      <div className="space-y-8">
          {data.questionInsights.map((qInsight, qIdx) => (
            <div key={qIdx} className="bg-white rounded-xl shadow-sm border border-slate-200 p-8">
              <div className="flex items-start space-x-3 mb-8 border-b border-slate-100 pb-5">
                <ListBulletIcon className="h-7 w-7 text-indigo-600 flex-shrink-0 mt-0.5" />
                <h2 className="text-xl font-bold text-slate-900 leading-snug">{qInsight.question}</h2>
              </div>
              <div className="grid grid-cols-1 gap-6">
                {qInsight.corePoints.map((point, idx) => (
                  <div key={idx} className="pl-6 border-l-[3px] border-slate-100 hover:border-indigo-500 transition-colors">
                    <div className="flex justify-between mb-2">
                      <h3 className="font-bold text-slate-800 text-lg">{point.label}</h3>
                      <span className="text-sm font-bold text-indigo-600 bg-indigo-50 px-2 py-1 rounded">{point.percentage}%</span>
                    </div>
                    <p className="text-slate-600 mb-3">{point.description}</p>
                    
                    {/* Updated Quotes Display */}
                    {point.quotes && point.quotes.length > 0 && (
                       <div className="mt-3 bg-slate-50 rounded-lg p-3 border border-slate-100">
                          <div className="flex items-center text-[10px] text-indigo-500 font-bold uppercase tracking-wide mb-2">
                            <ChatBubbleBottomCenterTextIcon className="w-3 h-3 mr-1" />
                            用户原声
                          </div>
                          <ul className="space-y-2">
                            {point.quotes.map((quote, qIdx2) => (
                              <li key={qIdx2} className="text-xs text-slate-600 leading-relaxed">
                                <span className="font-semibold text-indigo-600 mr-1.5">{quote.source}</span>
                                <span className="italic text-slate-500">"{quote.text}"</span>
                              </li>
                            ))}
                          </ul>
                       </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
      </div>
    </div>
  );
});

export default ResultsDashboard;